[2025-06-01T15:57:44.365+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover manual__2025-06-01T15:57:41.868908+00:00 [queued]>
[2025-06-01T15:57:44.377+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover manual__2025-06-01T15:57:41.868908+00:00 [queued]>
[2025-06-01T15:57:44.377+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-01T15:57:44.394+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): entrenar_y_promover> on 2025-06-01 15:57:41.868908+00:00
[2025-06-01T15:57:44.401+0000] {standard_task_runner.py:60} INFO - Started process 46777 to run task
[2025-06-01T15:57:44.413+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'entrenamiento_modelos_regresion', 'entrenar_y_promover', 'manual__2025-06-01T15:57:41.868908+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/entrenamiento_modelos_regresion_dag.py', '--cfg-path', '/tmp/tmpr15isjs5']
[2025-06-01T15:57:44.421+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask entrenar_y_promover
[2025-06-01T15:57:44.595+0000] {task_command.py:423} INFO - Running <TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover manual__2025-06-01T15:57:41.868908+00:00 [running]> on host f142218a01ee
[2025-06-01T15:57:44.777+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='entrenamiento_modelos_regresion' AIRFLOW_CTX_TASK_ID='entrenar_y_promover' AIRFLOW_CTX_EXECUTION_DATE='2025-06-01T15:57:41.868908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-01T15:57:41.868908+00:00'
[2025-06-01T15:57:47.924+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:47 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-01T15:57:47.946+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:50 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-01T15:57:47.952+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:52 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-01T15:57:47.954+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:54 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-01T15:57:50.809+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:57:50 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-01T15:57:58.507+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:57:58 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-01T15:58:01.677+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:01 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest at: http://mlflow:5000/#/experiments/1/runs/f2fad1b6f456497eb23d0cae0742b589.
[2025-06-01T15:58:01.677+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:01 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-01T15:58:05.554+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:05 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-01T15:58:05.644+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:05 INFO mlflow.tracking._tracking_service.client: üèÉ View run CatBoost at: http://mlflow:5000/#/experiments/1/runs/ba0b34a4ac0a460889431c12d32993e9.
[2025-06-01T15:58:05.644+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:05 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-01T15:58:09.905+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:09 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-01T15:58:09.989+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:09 INFO mlflow.tracking._tracking_service.client: üèÉ View run SVR at: http://mlflow:5000/#/experiments/1/runs/c4cab0bef2d94aefb8af4b64c45dbf0e.
[2025-06-01T15:58:09.990+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:09 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-01T15:58:10.102+0000] {logging_mixin.py:188} WARNING - Successfully registered model 'mejor_modelo_orquestado'.
[2025-06-01T15:58:10.273+0000] {logging_mixin.py:188} WARNING - 2025/06/01 15:58:10 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: mejor_modelo_orquestado, version 1
[2025-06-01T15:58:10.273+0000] {logging_mixin.py:188} WARNING - Created version '1' of model 'mejor_modelo_orquestado'.
[2025-06-01T15:58:10.276+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:88 FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-01T15:58:10.319+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:91 FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-01T15:58:10.371+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-01T15:58:10.397+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=entrenamiento_modelos_regresion, task_id=entrenar_y_promover, execution_date=20250601T155741, start_date=20250601T155744, end_date=20250601T155810
[2025-06-01T15:58:10.473+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-01T15:58:10.504+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
